Add warnings for explicit choose and old VC gen
epfl-lara/stainless pull request #1336
Opened 2022-11-14 12:13 UTC by mario-bucev

2022-11-14 19:57 UTC, vkuncak requested changes

2022-11-14 19:57 UTC, vkuncak commented on frontends/scalac/src/main/scala/stainless/frontends/scalac/CodeExtraction.scala
> +      ctx.reporter.warning(tr.pos, "`choose` expressions are untamed wild beasts to use with care. See https://github.com/epfl-lara/stainless/issues/1180 for more details")
Let's try to have a more serious comment here, saying "choose expressions may be unsafe due to difficulty in checking their realizability automatically"

2022-11-14 21:30 UTC, vkuncak commented
Another thing that might help users understand trusted proof base would be if we could print a record of the pipeline invoked in a given verification run, indicating in one line concise string whether any of the options that may increase trusted proof base were invoked in a given verification run:
- whether --admit-vcs was used (empty string if not)
- whether termination was turned off
- whether cache was used (empty if not)
- whether antialiasing and imperative elimination were used (empty if not)
- which smt solvers were invoked
- whether type encoding did anything (empty string if not)
- whether non-library extern functions were used
- whether batch mode was on
- full path of config file(s) used, if any

2022-11-15 04:50 UTC, mario-bucev commented on frontends/scalac/src/main/scala/stainless/frontends/scalac/CodeExtraction.scala
> +      ctx.reporter.warning(tr.pos, "`choose` expressions are untamed wild beasts to use with care. See https://github.com/epfl-lara/stainless/issues/1180 for more details")
True, thank you for the advice

2022-11-15 05:28 UTC, mario-bucev commented
I like this idea. I'll check what should be done to integrate this feature, ideally within this PR.

2022-11-17 07:06 UTC, mario-bucev commented
I've pushed what I hope corresponds to the above comment. Here is the concise summary printed for `ScalaList` (after the verification report):
```
[  Info  ] Verification pipeline summary:
[  Info  ]   cache, anti-aliasing, type encoding, choose injection, nativez3
```
With `--extended-summary`, we have extra information:
```
[  Info  ] Verification pipeline summary:
[  Info  ]   Cache used
[  Info  ]   Anti-aliasing phase transformed the following functions:
[  Info  ]     length
[  Info  ]   Type-encoding transformed the following:
[  Info  ]     -Functions:
[  Info  ]       ++, ::, head, length, map, tail
[  Info  ]     -Classes:
[  Info  ]       Cons, List, Nil
[  Info  ]   Choose injected in the following functions:
[  Info  ]     -User:
[  Info  ]       ++, ::, head, length, map, tail
[  Info  ]   Solvers used: nativez3
[  Info  ]   Processing mode: partial
```
The `choose` injected in functions `++`, etc. are for their copies, not the original ones. How could we convey such information? (I'm thinking of something like "`++` (derived from original `++`)")

2022-11-17 08:47 UTC, vkuncak commented
If the function was copied, that's similar from user point of view as if it was modified, so no need for that.

2022-11-17 08:49 UTC, merged